### ISSUE TITLE
rework tokenizer to be compatible with huggingface transformers `>=4.34.0`

### ISSUE THREAD

**Issue by mivanit** [understanding-search/maze-transformer#199]
a bunch of things change, and our constructor no longer works. we apparently need to override a `get_vocab()` method, but that alone doesn't fix it

this was first noted in #198

**Comment by aaron-sandoval** [comment]
@mivanit I talked about this issue with Alex and what he'd done on #208. There appear to be at least 2 distinct issues here.
1. Changes in `transformer_lens.HookedTransformer.set_tokenizer` cause `HuggingMazeTokenizer` to sometimes try to download our tokenizer from HF. You and I both have this issue, but Alex never has.
  - I made a naive one-line band-aid in #209 
  - I have no idea if this quick fix will break other things
3. The behavior of the `PreTrainedTokenizer` during actual tokenization has changed
  - This is what Alex has been working on, I haven't touched it yet
  - Alex believed that his approach in #208 was just continuing to build on unstable foundations. Do you agree with him that putting a tokenizer on hugging face is the proper way to solve this issue? Is that the approach you'd like me to take?
