### ISSUE TITLE
Create intro notebooks

### ISSUE THREAD

**Issue by valedan** [understanding-search/maze-transformer#56]
A notebook to demonstrate the main features and typical workflow for this project.

```[tasklist]
- [x] Maze generation
- [ ] Maze tokenization (blocked until new tokenizer is ready)
- [ ] Dataset creation (blocked until the new tokenizer is ready)
- [ ] Model training (blocked until the new tokenizer is ready)
```

**Comment by rusheb** [comment]
As agreed with the team offline, I am planning to drop the documentation tasks for the time being until we have a working model and a better idea of our roadmap. I think if I do docs at this point there’s a risk of everything changing and having to throw a lot of things out.
